FROM python:3.8

COPY requirements.txt requirements.txt
RUN apt-get update
RUN apt-get install g++
RUN apt-get install -y npm

RUN pip install -r requirements.txt

COPY . /app
WORKDIR /app

RUN npm ci --prefix app/static/
ENV FLASK_ENV=docker
# Get this from docker-compose
# EXPOSE 5001
