"""drop col

Revision ID: 3128e55e1eb2
Revises: d8a301f226c4
Create Date: 2022-03-15 00:43:09.417297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3128e55e1eb2'
down_revision = 'd8a301f226c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guessing_game_entity_facet_value', 'int_val')
    op.create_unique_constraint(None, 'guessing_game_user_access', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guessing_game_user_access', type_='unique')
    op.add_column('guessing_game_entity_facet_value', sa.Column('int_val', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
