"""adding words per player to game table

Revision ID: 3efe8111ce26
Revises: e36324647c2d
Create Date: 2020-04-25 17:21:33.283192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efe8111ce26'
down_revision = 'e36324647c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('words_per_player', sa.Integer(), nullable=True))
    op.execute('UPDATE game SET words_per_player = 5;')
    op.alter_column('game', 'words_per_player', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'words_per_player')
    # ### end Alembic commands ###
