"""change some fk names

Revision ID: 46b108c397bb
Revises: ec79979db271
Create Date: 2022-03-14 00:24:28.787277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b108c397bb'
down_revision = 'ec79979db271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guessing_game_day_user_progress_attempt_entity_id_fkey', 'guessing_game_day_user_progress_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'guessing_game_day_user_progress_attempt', 'guessing_game_entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guessing_game_day_user_progress_attempt', type_='foreignkey')
    op.create_foreign_key('guessing_game_day_user_progress_attempt_entity_id_fkey', 'guessing_game_day_user_progress_attempt', 'guessing_game_day', ['entity_id'], ['id'])
    # ### end Alembic commands ###
