"""adding salad bowl word

Revision ID: 62237ad5a761
Revises: b9604ecfc5f6
Create Date: 2020-03-21 19:07:17.996265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62237ad5a761'
down_revision = 'b9604ecfc5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salad_bowl_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salad_bowl_word')
    # ### end Alembic commands ###
