"""owner for guessing game

Revision ID: 71bb662f1e13
Revises: 78f008dc7fae
Create Date: 2022-03-13 18:57:35.843181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bb662f1e13'
down_revision = '78f008dc7fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessing_game', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guessing_game', 'user', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guessing_game', type_='foreignkey')
    op.drop_column('guessing_game', 'owner_user_id')
    # ### end Alembic commands ###
