"""entry code for guessing game

Revision ID: 78f008dc7fae
Revises: 9e2784a5c428
Create Date: 2022-03-13 18:43:15.135113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f008dc7fae'
down_revision = '9e2784a5c428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessing_game', sa.Column('entry_code_hash', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'login_attempt', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_attempt', type_='unique')
    op.drop_column('guessing_game', 'entry_code_hash')
    # ### end Alembic commands ###
