"""allow for fractional portions of currency

Revision ID: 7e74338591c0
Revises: fd5b9192b13c
Create Date: 2020-04-26 20:15:38.819508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e74338591c0'
down_revision = 'fd5b9192b13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banker_currency', sa.Column('amount_temp', sa.Float(), nullable=False))
    op.drop_column('banker_currency', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banker_currency', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('banker_currency', 'amount_temp')
    # ### end Alembic commands ###
