"""adding round number to round table

Revision ID: 82b437f84a42
Revises: 992fad75944c
Create Date: 2020-03-22 01:06:31.660425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b437f84a42'
down_revision = '992fad75944c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('round_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'round', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'round', type_='unique')
    op.drop_column('round', 'round_number')
    # ### end Alembic commands ###
