"""metadata for stuff

Revision ID: 9680803b1df5
Revises: ee6806937977
Create Date: 2022-03-19 21:32:09.024712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9680803b1df5'
down_revision = 'ee6806937977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessing_game', sa.Column('description', sa.String(length=512), nullable=True))
    op.add_column('guessing_game_entity', sa.Column('message', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guessing_game_entity', 'message')
    op.drop_column('guessing_game', 'description')
    # ### end Alembic commands ###
