"""adding round table

Revision ID: 992fad75944c
Revises: 62237ad5a761
Create Date: 2020-03-22 01:05:13.428999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992fad75944c'
down_revision = '62237ad5a761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'salad_bowl_word', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salad_bowl_word', type_='unique')
    op.drop_table('round')
    # ### end Alembic commands ###
