"""add team id to guessed word table

Revision ID: 9b4c9ba2b6e5
Revises: 043244e70763
Create Date: 2020-03-22 15:14:33.701179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4c9ba2b6e5'
down_revision = '043244e70763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessed_word', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'guessed_word', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guessed_word', type_='foreignkey')
    op.drop_column('guessed_word', 'team_id')
    # ### end Alembic commands ###
