"""add facet shorthand

Revision ID: a1dd7c94d106
Revises: 118b5210a2c7
Create Date: 2022-03-22 02:09:49.813641

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1dd7c94d106'
down_revision = '118b5210a2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessing_game_facet', sa.Column('short_label', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guessing_game_facet', 'short_label')
    # ### end Alembic commands ###
