"""adding second per turn to round table

Revision ID: a3c9ef98c3b0
Revises: 3e3bc827140b
Create Date: 2020-04-26 17:51:11.960189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c9ef98c3b0'
down_revision = '3e3bc827140b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('seconds_per_turn', sa.Integer(), nullable=True))
    op.execute('UPDATE round SET seconds_per_turn = 60;')
    op.alter_column('round', 'seconds_per_turn', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round', 'seconds_per_turn')
    # ### end Alembic commands ###
