"""adding started at and completed at to the game table

Revision ID: b9604ecfc5f6
Revises: eb08c53b7f2c
Create Date: 2020-03-21 18:47:56.002815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9604ecfc5f6'
down_revision = 'eb08c53b7f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('game', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'started_at')
    op.drop_column('game', 'completed_at')
    # ### end Alembic commands ###
