"""capture user guesses

Revision ID: e0f788e32dcc
Revises: fde2528ce475
Create Date: 2022-03-13 23:52:26.979295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f788e32dcc'
down_revision = 'fde2528ce475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guessing_game_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_start_at', sa.DateTime(), nullable=False),
    sa.Column('day_end_at', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['guessing_game_entity.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['guessing_game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessing_game_day_user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guessing_game_day_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guess_count', sa.Integer(), nullable=True),
    sa.Column('guessed_correctly_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guessing_game_day_id'], ['guessing_game_day.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessing_game_day_user_progress_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guessing_game_day_user_progress_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['guessing_game_day.id'], ),
    sa.ForeignKeyConstraint(['guessing_game_day_user_progress_id'], ['guessing_game_day_user_progress.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('guessing_game', sa.Column('max_guesses', sa.Integer(), nullable=True))
    op.add_column('guessing_game', sa.Column('allow_repeats', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guessing_game', 'allow_repeats')
    op.drop_column('guessing_game', 'max_guesses')
    op.drop_table('guessing_game_day_user_progress_attempt')
    op.drop_table('guessing_game_day_user_progress')
    op.drop_table('guessing_game_day')
    # ### end Alembic commands ###
