"""add expected complete_at to turn table

Revision ID: e36324647c2d
Revises: 9b4c9ba2b6e5
Create Date: 2020-03-22 15:56:11.259830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36324647c2d'
down_revision = '9b4c9ba2b6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turn', sa.Column('expected_complete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turn', 'expected_complete_at')
    # ### end Alembic commands ###
