"""change some fk names

Revision ID: ec79979db271
Revises: e0f788e32dcc
Create Date: 2022-03-14 00:21:35.086661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec79979db271'
down_revision = 'e0f788e32dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'guessing_game_day', ['id'])
    op.add_column('guessing_game_day_user_progress', sa.Column('game_day_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'guessing_game_day_user_progress', ['id'])
    op.drop_constraint('guessing_game_day_user_progress_guessing_game_day_id_fkey', 'guessing_game_day_user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'guessing_game_day_user_progress', 'guessing_game_day', ['game_day_id'], ['id'])
    op.drop_column('guessing_game_day_user_progress', 'guessing_game_day_id')
    op.add_column('guessing_game_day_user_progress_attempt', sa.Column('game_day_user_progress_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'guessing_game_day_user_progress_attempt', ['id'])
    op.drop_constraint('guessing_game_day_user_progre_guessing_game_day_user_progr_fkey', 'guessing_game_day_user_progress_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'guessing_game_day_user_progress_attempt', 'guessing_game_day_user_progress', ['game_day_user_progress_id'], ['id'])
    op.drop_column('guessing_game_day_user_progress_attempt', 'guessing_game_day_user_progress_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessing_game_day_user_progress_attempt', sa.Column('guessing_game_day_user_progress_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'guessing_game_day_user_progress_attempt', type_='foreignkey')
    op.create_foreign_key('guessing_game_day_user_progre_guessing_game_day_user_progr_fkey', 'guessing_game_day_user_progress_attempt', 'guessing_game_day_user_progress', ['guessing_game_day_user_progress_id'], ['id'])
    op.drop_constraint(None, 'guessing_game_day_user_progress_attempt', type_='unique')
    op.drop_column('guessing_game_day_user_progress_attempt', 'game_day_user_progress_id')
    op.add_column('guessing_game_day_user_progress', sa.Column('guessing_game_day_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'guessing_game_day_user_progress', type_='foreignkey')
    op.create_foreign_key('guessing_game_day_user_progress_guessing_game_day_id_fkey', 'guessing_game_day_user_progress', 'guessing_game_day', ['guessing_game_day_id'], ['id'])
    op.drop_constraint(None, 'guessing_game_day_user_progress', type_='unique')
    op.drop_column('guessing_game_day_user_progress', 'game_day_id')
    op.drop_constraint(None, 'guessing_game_day', type_='unique')
    # ### end Alembic commands ###
