"""add it back

Revision ID: ee6806937977
Revises: 3128e55e1eb2
Create Date: 2022-03-15 00:43:21.153796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6806937977'
down_revision = '3128e55e1eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guessing_game_entity_facet_value', sa.Column('int_val', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guessing_game_entity_facet_value', 'int_val')
    # ### end Alembic commands ###
