"""guessing game tables

Revision ID: f5a8a5b8d255
Revises: 71bb662f1e13
Create Date: 2022-03-13 21:03:59.883190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a8a5b8d255'
down_revision = '71bb662f1e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guessing_game_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['guessing_game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessing_game_facet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('facet_type', sa.Enum('INTEGER', 'ENUM', 'BOOLEAN', name='guessinggamefacettype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['guessing_game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessing_game_facet_enum_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('facet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facet_id'], ['guessing_game_facet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessing_game_facet_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.Enum('DEGREES_OF_CLOSENESS', 'MINIMUM', 'MAXIMUM', name='guessinggamefacetpropertytype'), nullable=False),
    sa.Column('int_val', sa.Integer(), nullable=True),
    sa.Column('facet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facet_id'], ['guessing_game_facet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessing_game_entity_facet_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facet_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('int_val', sa.String(length=64), nullable=True),
    sa.Column('enum_option_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['guessing_game_entity.id'], ),
    sa.ForeignKeyConstraint(['enum_option_id'], ['guessing_game_facet_enum_option.id'], ),
    sa.ForeignKeyConstraint(['facet_id'], ['guessing_game_facet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guessing_game_entity_facet_value')
    op.drop_table('guessing_game_facet_property')
    op.drop_table('guessing_game_facet_enum_option')
    op.drop_table('guessing_game_facet')
    op.drop_table('guessing_game_entity')
    # ### end Alembic commands ###
