"""currecneis need values

Revision ID: fd5b9192b13c
Revises: b3ec0752cee9
Create Date: 2020-04-26 20:06:59.064842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5b9192b13c'
down_revision = 'b3ec0752cee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'banker', ['id'])
    op.add_column('currency', sa.Column('value', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'currency', ['id'])
    op.create_unique_constraint(None, 'currency_history', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_history', type_='unique')
    op.drop_constraint(None, 'currency', type_='unique')
    op.drop_column('currency', 'value')
    op.drop_constraint(None, 'banker', type_='unique')
    # ### end Alembic commands ###
