"""no null enum

Revision ID: fde2528ce475
Revises: f5a8a5b8d255
Create Date: 2022-03-13 21:37:43.385563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde2528ce475'
down_revision = 'f5a8a5b8d255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'guessing_game_entity', ['id'])
    op.create_unique_constraint(None, 'guessing_game_entity_facet_value', ['id'])
    op.create_unique_constraint(None, 'guessing_game_facet', ['id'])
    op.alter_column('guessing_game_facet_enum_option', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'guessing_game_facet_enum_option', ['id'])
    op.create_unique_constraint(None, 'guessing_game_facet_property', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guessing_game_facet_property', type_='unique')
    op.drop_constraint(None, 'guessing_game_facet_enum_option', type_='unique')
    op.alter_column('guessing_game_facet_enum_option', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'guessing_game_facet', type_='unique')
    op.drop_constraint(None, 'guessing_game_entity_facet_value', type_='unique')
    op.drop_constraint(None, 'guessing_game_entity', type_='unique')
    # ### end Alembic commands ###
